name: deploy-mdb-atlas-app-service
run-name: ${{ github.actor }} deploys an app on the Atlas App Service
on: [workflow_dispatch]
env:
  NODE_VERSION: 18
  APP_ID: ${{ vars.APP_ID }}
  APP_NAME: ${{ vars.APP_NAME }}
  PUBLIC_API_KEY: ${{ vars.PUBLIC_API_KEY }}
  PRIVATE_API_KEY: ${{ secrets.PRIVATE_API_KEY }}
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: find thbaankk
      - name: Install dependencies
        working-directory: ./thbaankk
        run: npm i
      - name: Build
        working-directory: ./thbaankk
        run: npm run build
      - name: Create data directory
        run: mkdir -p ./data/files
      - name: Copy dist directory
        run: cp -R ./thbaankk/dist/* ./data/files
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./data
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install -g mongodb-realm-cli
      - name: Create build artifact directory
        run: mkdir -p build-artifact
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build-artifact
      - name: Login
        run: realm-cli login --api-key ${{ env.PUBLIC_API_KEY }} --private-api-key ${{ env.PRIVATE_API_KEY }} -y
      - name: Pull changes
        run: realm-cli pull --remote ${{ env.APP_ID }}
      - name: Copy build artifact
        run: cp -R ./build-artifact/* ./${{ env.APP_NAME}}/hosting
      - name: Push changes
        working-directory: ./${{ env.APP_NAME }}
        run: realm-cli push --remote ${{ env.APP_ID }} -s -c -y
        